### ISSUE TITLE
Consider introducing a restart delay to prevent WAL corruption issues

### ISSUE THREAD

**Issue by aaronc** [regen-network/cosmosd#6] opened 2019-09-17 17:13 UTC
Brought up by @chris-remus in the validator call

**Comment by aaronc** [comment] 2019-09-17 17:48
Potential solutions would be to:
1) introduce a short delay before shutting down or starting the daemon - maybe 1s
2) instructing people to setup such a delay in systemd

Thoughts @ethanfrey? If you have references to how and when this issue occurs please share @chris-remus

**Comment by ethanfrey** [comment] 2019-09-18 11:02
I have a question about the corruption issue - where does it happen and what are the causes and symptoms (gladly link to cosmos-sdk or tendermint issues as a response).

As to shutdown time, we can easily add a delay, this would be in the Watcher when it detects the upgrade. I guess a default timeout that can be overriden by an env variable? Maybe have to update tests as well, definitely docs. The question with adding delays is interesting, as they usually mask problems that are hard to debug later in those rare cases they occur.

Since we kill the process in BeginBlock, when the last committed block is long flushed to disk, and we should not have anything to sync, I am curious what the circumstances are that cause the corruption, I would prefer to listen to an actual signal from the binary saying "safe to kill me" rather than add a random timeout.

**Comment by ethanfrey** [comment] 2019-09-30 18:03
I asked Zaki about this and it seems like it was fixed in recent tendermint versions, and there was no clear issue or documented work-around, so I wonder if we really want to deal with this. I would like a clear reference to a discussion with core tendermint team and some evidence that a sleep (and how long?) will avoid this. I can add in 0.5s sleep now, but I feel it just masks some other problem.

As said, we kill the process after it freezes in BeginBlock. Does that mean the tendermint block database was not flushed first?

------


Ethan Frey 4:30 PM
I keep hearing comments about be careful about killing xrnd / gaiad too fast, you might have WAL corruption issues. But no one can point me to an issue on this.
Anyone know what this is? A rumor, or an actual issue we need to be careful about?
Thanks

zaki 4:41 PM
I’ve seen WAL corruption in Tendermint 0.31.5
I believe it might be less of a problem at higher versions
I believe it’s real

Ethan Frey 4:45 PM
Are there any tracking issues?
And is this the WAL for goleveldb? Or the tendermint wal file?
As I recall, the tendermint WAL was only written, never read, and meant for some backup replay tx stuff for an old prototype (pre 0.7). This may have well changed since 0.25 which was when I looked into it

zaki 4:51 PM
As I said, I believe it’s been fixed in master
But hasn’t propagated to the Cosmos hub

**Comment by aaronc** [comment] 2019-10-24 18:43
@ethanfrey is this still relevant?

**Comment by ethanfrey** [comment] 2019-10-27 14:27
I think it is not.
A few "I believes" from Zaki isn't a strong argument, but without any reported issues either demonstrating this issue or the fix, I would close it as irrelevant for the 0.38+ sdk that will have a new tendermint and is the only sdk we target with real-world usage of cosmosd

**Closed as completed by ethanfrey** 2019-10-27 14:27 UTC
