### ISSUE TITLE
Non-deterministic behavior when hitting upgrade height

### ISSUE THREAD

**Issue by aaronc** [regen-network/cosmosd#7] opened 2019-09-22 02:17 UTC
This must have something to do with a race condition between the goroutine scanning for the upgrade string and the one listening for process exist. Sometimes it will hit the upgrade height and try to download the binary, other times it will just exit not seeing the upgrade string. The behavior should be deterministic - if there was an upgrade string and the process exited shortly after, it should still catch the upgrade string.

For example, no upgrade URL found this time:
```
I[2019-09-21|22:12:51.685] Starting ABCI with Tendermint                module=main 
E[2019-09-21|22:12:51.799] UPGRADE "amazonas" NEEDED at height 50: https://git.io/Jesm1?checksum=sha256:e07f5edd22ffd754c779cf794f4fcc052c366b738d585c1011ff60d16a62ca72 module=main 
I[2019-09-21|22:12:51.799] Looking for upgrade script /Users/arc/.xrnd/config/do-upgrade module=main 
exit status 2
```

Running again, an upgrade URL found (but some other error):
```
I[2019-09-21|22:13:01.223] Starting ABCI with Tendermint                module=main 
E[2019-09-21|22:13:01.341] UPGRADE "amazonas" NEEDED at height 50: https://git.io/Jesm1?checksum=sha256:e07f5edd22ffd754c779cf794f4fcc052c366b738d585c1011ff60d16a62ca72 module=main 
I[2019-09-21|22:13:01.341] Looking for upgrade script /Users/arc/.xrnd/config/do-upgrade module=main 
invalid checksum: invalid checksum: encoding/hex: invalid byte: U+0020 ' '
downloading reference link https://git.io/Jesm1?checksum=sha256:e07f5edd22ffd754c779cf794f4fcc052c366b738d585c1011ff60d16a62ca72 module=main
main.GetDownloadURL
        /Users/arc/cosmos-binmgr/upgrade.go:109
main.DownloadBinary
        /Users/arc/cosmos-binmgr/upgrade.go:54
main.DoUpgrade
        /Users/arc/cosmos-binmgr/upgrade.go:40
main.LaunchProcess
        /Users/arc/cosmos-binmgr/process.go:45
main.Run
        /Users/arc/cosmos-binmgr/main.go:22
main.main
        /Users/arc/cosmos-binmgr/main.go:9
runtime.main
        /Users/arc/go/go1.12.6/src/runtime/proc.go:200
runtime.goexit
        /Users/arc/go/go1.12.6/src/runtime/asm_amd64.s:1337
cannot download binary
main.DoUpgrade
        /Users/arc/cosmos-binmgr/upgrade.go:41
main.LaunchProcess
        /Users/arc/cosmos-binmgr/process.go:45
main.Run
        /Users/arc/cosmos-binmgr/main.go:22
main.main
        /Users/arc/cosmos-binmgr/main.go:9
runtime.main
        /Users/arc/go/go1.12.6/src/runtime/proc.go:200
runtime.goexit
        /Users/arc/go/go1.12.6/src/runtime/asm_amd64.s:1337
```

**Comment by aaronc** [comment] 2019-09-26 13:29
@ethanfrey some people ran into this - it still worked but more glitchy

**Comment by yn-alex** [comment] 2019-09-26 15:16
I'll post the logs during the live amazonas upgrade. 
I had the same error for a few times and at some point it worked. Each time, cosmosd exited with an exit code 2 then systemd restarted the process according to my service file configuration (Restart always; RestartSec=3).
[temp.txt](https://github.com/regen-network/cosmosd/files/3658524/temp.txt)

**Comment by ethanfrey** [comment] 2019-10-29 09:45
This needs more investigation. Unclear exactly what conditions cause the error, which is needed to make a proper fix. Relevant code seems to be:

https://github.com/regen-network/cosmosd/blob/8d8b8dd4fc182be85600a189fce237f1f9f1cf2a/process.go#L90-L126

https://github.com/regen-network/cosmosd/blob/8d8b8dd4fc182be85600a189fce237f1f9f1cf2a/scanner.go#L21-L44

**Comment by charymalloju** [comment] 2019-11-04 14:07
Case 1: We think the problem is in waitScan(), where we are reading the function parameter of scan and passing it to WaitForUpdate(). But there the passed parameter is scanOut instead of scan, which always ignores scanErr.

https://github.com/regen-network/cosmosd/blob/8d8b8dd4fc182be85600a189fce237f1f9f1cf2a/process.go#L101


Case 2: In WaitForUpdate(), we are not checking length of substring and directly taking index values of substring array, which may cause the error.

https://github.com/regen-network/cosmosd/blob/8d8b8dd4fc182be85600a189fce237f1f9f1cf2a/scanner.go#L30-#L37

**Comment by ethanfrey** [comment] 2019-11-05 08:43
Case 1 is definitely a bug/typo. Not sure if this is the cause of the behavior, but good catch and very nice to fix.

Case 2, I understood regexp package to return all items if there is a match. Since I check there is a match, then I know `subs[0]` is the full text matched, `subs[1]` is the name, `subs[2]` is the height, and `subs[3]` is the info - based on the `upgradeRegexp` shape. 
Maybe I misunderstood, and explain more if so, but I think this is proper based on the rexexp documentation.

**Comment by clevinson** [comment] 2020-02-25 15:12
Nobody reported this problem during hte last testnet, so marking as closed.

**Closed as completed** 2020-02-25 15:12 UTC
